### ISSUE TITLE
Add an RSS / Atom feed for releases

### ISSUE THREAD

**Issue by substrae** [hydrogen-css/hydrogen#231]
### Dependencies
- #233 

### Subtasks
- [x] Add the release type to the `entry`
- [x] Add breaking flags to the `entry`
- [x] Research and implement a standardized image
- [x] Remove the release title from the `entry` content, as it's duplicated in the title element
- [x] Ensure all items are properly bulleted
